version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  machine_setup_db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rahipatel@1994
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  machine_setup:
    container_name: my_app
    build:
      context: ./Machine_Setup_worksheet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - machine_setup_db
      - redis
    volumes:
      - ./Machine_Setup_worksheet/DataProtection-Keys:/app/DataProtection-Keys
    environment:
      - ConnectionStrings__DefaultConnection=Server=machine_setup_db;Database=MachineSetup;User ID=sa;Password=Rahipatel@1994;TrustServerCertificate=true;

volumes:
  dataprotection-keys:
  sqlserverdata:
  redisdata:

  
  
