services:
  - type: web
    name: machine-setup-app
    env: docker
    image: rahiblogger/machine_setup_app:v1
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Server=machine_setup_db,1433;Database=MachineSetup;User ID=sa;Password=Rahipatel@1994;TrustServerCertificate=true;
    disk:
      size: 1GB
    secrets:
      - name: dataprotection-keys
        path: /app/DataProtection-Keys
      - name: webdata
        path: /data/images

  - type: web
    name: machine-setup-db
    env: docker
    image: mcr.microsoft.com/mssql/server:latest
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        value: Rahipatel@1994

  - type: redis
    name: redis
    env: docker
    image: redis:latest

secrets:
  - name: dataprotection-keys
    path: ./Machine_Setup_worksheet/DataProtection-Keys
  - name: webdata
    path: ./Machine_Setup_worksheet/wwwroot/images
